export * from './generated/health/health';
export * from './generated/model';
export { customInstance, ApiClientError } from './axios-instance';

// 契约出口收敛：前端只从 @starter/api-client 获取领域模型与校验 schema，
// 不再直接依赖 @starter/contracts（注：UserVo 等模型名与 generated 重名，
// 故这里选择性 re-export，避免 export * 的命名歧义）。
export {
  LoginSchema,
  RefreshSchema,
  CreateAdminAccountSchema,
  UpdateAdminAccountSchema,
  CreateRoleSchema,
  UpdateRoleSchema,
  CreateMenuSchema,
  UpdateMenuSchema,
  UpdateSelfSchema,
  ChangePasswordSchema,
  SaveAccountMenusSchema,
  SystemConfigSchema,
  ConfigUpdateItemSchema,
  BatchUpdateConfigsSchema,
  UpdateConfigSchema,
  AuditLogQuerySchema,
  AuditLogItemSchema,
  ClearAuditLogsResultSchema,
  CacheKeySchema,
  CacheStatsSchema,
  DeleteCacheKeysResultSchema,
  CacheListQuerySchema,
  DeleteCacheKeysInputSchema,
  ClearCachePatternInputSchema,
  SysDictItemSchema,
  SysDictTypeSchema,
  CreateDictTypeSchema,
  UpdateDictTypeSchema,
  CreateDictItemSchema,
  UpdateDictItemSchema,
  UploadFileSchema,
} from '@starter/contracts';
export type {
  AdminMe,
  AuthResult,
  LoginInput,
  RefreshInput,
  AdminAccount,
  CreateAdminAccountInput,
  UpdateAdminAccountInput,
  AdminRole,
  PermissionCode,
  CreateRoleInput,
  UpdateRoleInput,
  AdminMenu,
  AdminMenuNode,
  MenuType,
  CreateMenuInput,
  UpdateMenuInput,
  UpdateSelfInput,
  ChangePasswordInput,
  AccountMenuOverride,
  AccountMenuType,
  AccountMenusResult,
  SaveAccountMenusInput,
  SystemConfig,
  ConfigUpdateItem,
  BatchUpdateConfigsInput,
  UpdateConfigInput,
  AuditLogItem,
  AuditLogQuery,
  ClearAuditLogsResult,
  CacheKey,
  CacheStats,
  DeleteCacheKeysResult,
  CacheListQuery,
  DeleteCacheKeysInput,
  ClearCachePatternInput,
  SysDictItem,
  SysDictType,
  CreateDictTypeInput,
  UpdateDictTypeInput,
  CreateDictItemInput,
  UpdateDictItemInput,
  UploadFile,
  UploadResult,
} from '@starter/contracts';
